---
title: "Analysis of bike sharing data"
author: "Elise Gourri, Emilia Marlene Ribeiro Peixoto, Pascal Albisser"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: TRUE
    code_folding: hide
---

```{r, message = FALSE, echo = FALSE}
library(kableExtra)
library(ggplot2)
library(dplyr)
library(data.table)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = function() {
  if (knitr::is_latex_output())
    "latex" else "pipe"
})
```

# Dataset

Our Dataset, pls run `scripts/download-data.R` first.

```{r}
data <- fread("data/trips_s.csv")
kable(head(data))
```


```{r}
data %>% 
  ggplot(mapping = aes(x = city, fill = city)) + 
    geom_bar() +
    labs(title = "Number of trips per city")
```




```{r}
data %>% 
  group_by(city, year_month = paste(format(started_at, "%Y-%m"), "-01", sep="")) %>% 
  summarise(n = n()) %>% 
  ggplot(mapping = aes(y = n, x = as.Date(year_month), group = city, colour = city)) + 
    geom_line() +
    geom_point() +
    labs(title = "Sum of trips per city and month", y = "number of trips", x = "")
```


# SVM

first chapter

# Neural Nets

second chapter

# And so on...

# Elise makes a test push